language: node_js
node_js:
  - node
deploy:
  provider: heroku
  app: radiant-falls-19131
  api_key:
    secure: XnB9tgG1AyMgAr9sIF5hj75BUBjhWKciHXHCITnPBePw3fK3GMqztIPvcSe8YZxBUuVgOm1h/H7n7FqXneaLvk/v12IVmhT6z3M1AZZdIHxcCn4DXB1u+NTbgwAMmWB4yEBl1iWkzpIdexzFxRP1pH2k4EKC5vyrZrAzYFqw5fpQ6L+POZS8oj1SCz0+7+ab6+8nRaSF5PE9XCmT2BIwKB67QKS8kh0cYmpAGEWN0lecFi4lHcVYkRg6RTr8CN0a43Qel16lgWI0sQYwO+u7xuc3nmiK/JSrENG+GrQPbA0E6VDZc1M1UHpyA67XtNuhAeZ8RHhkZCLVRUr8oZb6Gw0R5zPHTNt3mkT2FWpJ4rW7LF3ih86Ixtl+9QynyZ4cY+KZPyw8GuW7P4dDrUKaButnrqo5tnGPls2efxc/Bd5+hNSG3e7gutia6+jNISa8yjPpsrZJEY86FoGMeQ8HSsmEckLP1ECglOfp+5nxeFqnqT9Q5duHegg6dB19xl7qpGrrromnSg9UBLphxMiH81y32skh56GkvxT5FzyU5RSDZ8BKeZXnCYWw1H7Q/5BbXWvfshLiRQ4c7lpaP/69ycFsgsbWEDFLB7cL+EFN90AC6ybyibuXcxhZpdku4hl9pQ+h687T0fp8cQpbFlR1ydy7JFPWyjjMkJm0xqJyHIw=
