language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: y+F+Y3OXdS3ENdnc8Ajw7hniNb/b6YV6MfwdjDrE8+15yrPZPWg5M3lwODRxj4fCtmsWbzSZcxKXQkYwzowV1n2MFuEZNjdzvINDB8WaqGYpSAJRrOjFX79rWIBVH4HtfFEj/cwSYWk4okCvs/9hY3v0CFPQgOllIzTGJ8sWZ02y4LmHpm5rUGiRNZP5ucPMH39HU0fzdVgbvH9+fhNB0oKSuvk0jxueEqd5lxM+HWAGXdhdZddg49+/dkBa/3+P4RIIWokvpOHM96WtoRobV6reH+X6myNddDfmAJwoGPdMWZQERLKDqecfGeNcz5XLeWUZql2UQ7S04aGUkcna0eNiOeBZkDhQu8ontX5+JX7NFWMBPsIMHmqcPResf10mF20oAQoo9u8rvtMIjpXjMP7VDzA5B4v7RyFS1BdmNZNa0peHZPm7tH7DTnkreVFqwMUOQcE1mcOFqUQKmTxl4c9v8PfRR5YF/o/qVsPS6OTsSoa2/d09+XNZgaBCLCNlXHllKjIwNAqJqbcvh27J0NlDvGIOHqW7GLnrEDH1cCGCO7aqBmYBjIMXB+m2QS2Lmdq+mmZ7AuKNAVCz90+ioCe5qCRIEOyEILwFgMzrtS5ZXjND374oJf++J0OUs5ghqaV3sUz2m0im0RzPmqRICedFv6CyZTiRwcypdFcFRxQ=
